version: '3.9'

services:
  app:
    image: cooderl/wewe-rss:latest
    container_name: wewe-rss
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      # PostgreSQL 数据库连接地址 (使用现有 haoju-postgres 容器)
      - DATABASE_URL=postgresql://root:fuwenhao@host.docker.internal:5432/spider_gzh_db?schema=public&connect_timeout=30&pool_timeout=30
      # 数据库提供商设置为 postgresql
      - DATABASE_PROVIDER=postgresql
      # 服务接口请求授权码
      - AUTH_CODE=123567
      # 提取全文内容模式
      - FEED_MODE=fulltext
      # 定时更新订阅源Cron表达式
      - CRON_EXPRESSION=35 5,17 * * *
      # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=60
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=http://localhost:4000
      # 其他配置
      - HOST=0.0.0.0
      - PORT=4000
      - ENABLE_CLEAN_HTML=false
      - UPDATE_DELAY_TIME=60
      - PLATFORM_URL=https://weread.111965.xyz

