version: '3.8'

services:
  wewe-rss:
    image: cooderl/wewe-rss:latest
    container_name: wewe-rss
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      # PostgreSQL configuration
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: "postgresql://root:fuwenhao@host.docker.internal:5432/spider_gzh_db?schema=public&connect_timeout=30&pool_timeout=30"

      # Other configurations
      AUTH_CODE: "123567"
      HOST: "0.0.0.0"
      PORT: "4000"
      MAX_REQUEST_PER_MINUTE: "60"
      FEED_MODE: "fulltext"
      SERVER_ORIGIN_URL: "http://localhost:4000"
      CRON_EXPRESSION: "35 5,17 * * *"
      ENABLE_CLEAN_HTML: "false"
      UPDATE_DELAY_TIME: "60"
      PLATFORM_URL: "https://weread.111965.xyz"
    networks:
      - wewe-rss-network

networks:
  wewe-rss-network:
    driver: bridge